# Generated by Django 6.0.1 on 2026-03-07 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_miembro_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
        ),
    ]
