# Generated by Django 4.2.8 on 2026-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_miembro_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='curso',
        ),
        migrations.AddField(
            model_name='miembro',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='core.curso'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
