# Generated by Django 4.2.8 on 2026-05-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_miembro_curso_miembro_cursos_miembro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
